rule1:
  name: 'institutes1'
  conditions:
    - { field: 'department->id', content: 'http://uri.gbv.de/organization/isil/DE-84@department-2'}
  actions:
    - {field: 'availabilityplus->daiahint->label', content: 'institute'}
    - {field: 'availabilityplus->daiaaction->label', content: 'institute'}
rule2:
  name: 'institutes2'
  conditions:
    - { field: 'department->id', content: 'http://uri.gbv.de/organization/isil/DE-84@department-2'}
  actions:
    - {field: 'availabilityplus->daiahint->label', content: 'institute'}
    - {field: 'availabilityplus->daiaaction->label', content: 'institute'}