1ArticleFulltextFree:
  category: FreeAccess
  mandatory-field: url
  view-method: ajax/link-external.phtml
  856:
    conditions:
      - [field, 3, Volltext]
      - [field, z, 'kostenfrei|Kostenfrei|^OpenAccess Lizenz|Description of rights in Directory of Open Access Books|^OA$']
      - [indicator, 1, 4]
      - [indicator, 2, 0|1]
    u:
      - [name, url]
2ArticleFulltextFreeUrlParts:
  category: FreeAccess
  mandatory-field: url
  view-method: ajax/link-external.phtml
  856:
    conditions:
      - [field, u, 'doaj.org\/article|edocs.tib.eu\/files|tib.uni-hannover.de\/edoks\/|digibib.tu-bs.de|resolver.sub.uni-goettingen.de|resolver.staatsbibliothek-berlin.de|hdl.handle.net|lib.dr.iastate.edu|www.dzhw.eu\/pdf|www.his.de\/pdf|arxiv.org|publikationsserver.tu-braunschweig.de\/get|bib-pubdb1.desy.de\/record|inef.uni-due.de\/index.php?article_id=|kluedo.ub.uni-kl.de\/frontdoor\/index\/index\/docId\/|wiiw.ac.at|library.fes.de\/pdf-files|www.bis.org\/publ\/bppdf|www.bsu-bund.de\/SharedDocs\/pdf|www.bamf.de\/SharedDocs\/Anlagen\/DE\/Publikationen|bib-pubdb1.desy.de\/record|www.doabooks.org\/doab?func=fulltext|www.pharmazeutische-zeitung.de|clinicaltrials.gov\/show|www.jfe-steel.co.jp\/en\/research\/report\/|www.ressource-deutschland.de\/fileadmin\/|juser.fz-juelich.de\/record\/|www.qip-journal.eu\/index.php\/ams\/article\/download\/|www.ita.rwth-aachen.de\/global\/show_document.asp|opus.bibliothek.uni-wuerzburg.de\/files\/|kth.diva-portal.org\/smash\/record|www.teses.usp.br\/teses\/disponiveis\/|edoc.difu.de\/edoc.php|haab-digital.klassik-stiftung.de\/viewer|darwin-online.org.uk|www.doabooks.org|revistas.unam.mx|produccioncientificaluz.org']
      - [indicator, 1, 4]
      - [indicator, 2, 0|1]
    u:
      - [name, url]
3ArticleFulltextFreeUrlParts2:
  category: FreeAccess
  mandatory-field: url
  view-method: ajax/link-external.phtml
  856:
    conditions:
      - [field, u, 'doi.org|nbn-resolving.de|doaj.org\/article|www.doabooks.org\/doab\?func=fulltext']
      - [field, z, 'Kostenfrei|^OpenAccess Lizenz|Description of rights in Directory of Open Access Books|^OA$']
      - [indicator, 1, 4]
      - [indicator, 2, 0|1]
    u:
      - [name, url]
TestLabel:
  view-method: ajax/default.phtml
  245:
    a: 
      - [name, label]
TestLevel:
  view-method: ajax/default.phtml
  245:
    a: 
      - [name, level]
GBVILLTitle:
  category: GBVILL
  mandatory-field: url
  view-method: ajax/link-external.phtml
  245:
    a:
      - [name, url]
      - [replace, '(^.*$)', 'https://kxp.k10plus.de/DB=2.1/CMD?TRM=tpr($0)&ACT=SRCH']
  490:
    a:
      - [name, url]
      - [replace, '(^.*$)', 'https://kxp.k10plus.de/DB=2.1/CMD?TRM=tpr($0)&ACT=SRCH']
JournalsOnlinePrint:
  category: resolver
  view-method: ajax/link-jop.phtml
  mandatory-field: issn
  773:
    t:
      - [name, title]
    x:
      - [name, issn]
  952:
    d:
      - [name, volume]
    j:
      - [name, date]
    e:
      - [name, issue]
    h:
      - [name, pages]
DAIA:
  category: resolver
  view-method: ajax/link-daia.phtml
  mandatory-field: id
  '035':
    conditions:
      - [field, a, '\(DE-627\)([0-9xX]+)']
    a:
      - [name, id]
      - [replace, '\(DE-627\)([0-9xX]+)', 'ppn:$1']
#TODO Später anpassen?
ArticleFulltextFreeCollection:
  category: FreeAccessIndirect
  view-method: ajax/link-external.phtml
  912:
    conditions:
      - [field, a, 'OPENACCESS|GBV_DOAJ|Gutenberg|ZDB-94-OAB|ZDB-23-GOA|GBV_XBI|GBV_XAR|GBV_XCH|GBV_CTG']
    a:
      - [name, collection]

      
#TODO Später anpassen?
ArticleDirectLink:
  category: marcFulltextCheckPrep
  view-method: ajax/link-external.phtml
  856:
    conditions:
      - [field, 3, Volltext]
      - [indicator, 1, 4]
      - [indicator, 2, 0|1]
    u:
      - [name, url]
      
#TODO Später anpassen?
ArticleDirectLinkUrlParts:
  category: marcFulltextCheckPrep
  view-method: ajax/link-external.phtml
  856:
    conditions:
      - [field, u, 'doi.org']
    u:
      - [name, url]

