Signatur:
  name: 'Signatur'
  descripton: ''
  reason: ''
  date: ''
  creator: ''
  examples: ''
  details: ''
  conditions:
    - { field: 'availabilityplus->callnumber', content: '(.*):(.*)' }
  actions:
    - { field: 'availabilityplus->callnumber', content_field: 'availabilityplus->callnumber', pattern: '(.*):(.*)', replacement: '$2'}
