Case1:
  id: '80037908X'
  list: '1'
  driver: 'Solr'
  description: 'test description1'
  expected: 'test expected1'
  reason: ''
  date: ''
  creator: ''
  examples: ''
  rules: ''
  details: ''
Case2:
  id: '21262833X'
  list: '0'
  driver: 'Search2'
  description: 'test description2'
  expected: 'test expected2'
  reason: ''
  date: ''
  creator: ''
  examples: ''
  rules: ''
  details: ''