rule100:
  name: 'Signatur'
  conditions:
    - { field: 'label', content: '(.*):(.*)' }
  actions:
    - { field: 'callnumber', content_field: 'callnumber', pattern: ''(.*):(.*)', replacement: '$2'}
