rule100:
  name: 'Signatur'
  conditions:
    - { field: 'availabilityplus->callnumber', content: '(.*):(.*)' }
  actions:
    - { field: 'availabilityplus->callnumber', content_field: 'availabilityplus->callnumber', pattern: '(.*):(.*)', replacement: '$2'}
